name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - mkl < 2022
  - cudatoolkit
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - scikit-learn
  - pip:
    - pytorch-lightning==1.5.0
    - tensorboard==2.7.0
    - tabulate==0.8.9
    - tqdm==4.62.3
    - pillow==8.0.1
    - notebook
    - jupyterlab
    - matplotlib
    - seaborn
    - ipywidgets