#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=amn_probing
#SBATCH --ntasks=1
#SBATCH --time=10:00:00
#SBATCH --array=1-10%5
#SBATCH --output=job_logs/slurm_output_%A_%a.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/MALeViC/code

# Activate environment
source activate thesis

HPARAMS_FILE=$HOME/MALeViC/code/array_job_hyperparameters2.txt


# Run code
srun python -u amnesic_probing.py $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)