#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pm5
#SBATCH --nodes=1
#SBATCH --time=10:00:00
#SBATCH --output=job_logs/slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Make environment
# cd $HOME
# conda env create -f environment_gpu.yml

# Activate environment
source activate thesis

# Run code
cd $HOME/MALeViC/code
# srun python make_representations.py